---
- name: install docker and kubernetes
  yum: name=docker,git,golang,bridge-utils,e2fsprogs,net-tools
       enablerepo=rhel-7-server-extras-rpms,rhel-7-server-optional-rpms
       state=latest
  tags:
    - docker

# FIXME check if hostvars["ansible_interfaces"] contains docker0
- name: take down docker bridge
  command: ifconfig docker0 down
  ignore_errors: yes
  tags:
    - docker
- name: remove docker0 bridge
  command: brctl delbr docker0 
  ignore_errors: yes
  tags:
    - docker

- name: replace systemd service file, so that flannel is used
  copy: src=docker.service dest=/usr/lib/systemd/system/docker.service mode=0755 owner=root group=root backup=true
  tags: 
    - docker

- name: reload systemd because the unit file changed on disk
  command: systemctl daemon-reload
  tags:
    - docker
