---
# install pkg
- name: install etcd server packages
  yum: name={{ item }} state=present
  with_items: 
    - http://download.devel.redhat.com/brewroot/packages/etcd/0.4.6/0.12.el7/x86_64/etcd-0.4.6-0.12.el7.x86_64.rpm 
  tags:
    - etcd 

- name: be sure etcd is running and enabled
  service: name=etcd state=running enabled=yes
  tags:
    - etcd 

- name: generate flannel configuration
  template:
    src=flannel-config.json.j2
    dest=/tmp/flannel-config.json
    owner=root
    group=root
    mode=0644
  tags: 
    - etcd 
    - flannel

- name: flanneld configuration (copy script)
  template: src=config-flannel.sh.j2 dest=~/config-flannel.sh mode=755
  tags:
    - etcd
    - flannel

- name: flanneld configuration (run script)
  command: ~/config-flannel.sh
  tags:
    - etcd
    - flannel

- name: flanneld configuration (cleanup)
  file: name=~/config-flannel.sh state=absent
  tags:
    - etcd
    - flannel

