---
- name: bootstrap COPR maxamillion/origin-next/repo
  copy: src=origin-next.repo
        dest=/etc/yum.repos.d/
        owner=root group=root mode=0644

- name: enable maxamillion-origin-next repository
  ini_file: dest=/etc/yum.repos.d/origin-next.repo
            section=maxamillion-origin-next
            option=enabled
            value=1

- name: install OpenShift Origin 3
  yum: name=origin state=present

