# Handlers for restarting services
#

- name: restart docker
  action: service name=docker state=restarted

- name: restart flannel
  action: service name=flanneld state=restarted

- name: restart etcd
  service: name=etcd state=restarted
