---
- hosts: all
  sudo: yes

  roles:
    - common
    - docker
    - openshift-origin-next

- hosts: masters
  sudo: yes
  roles:
    - etcd
    - flannel

- hosts: minions
  sudo: yes
  roles:
    - flannel
