---
- hosts: all
  sudo: yes
  tasks:
    - name: "Build /etc/hosts on all hosts"
      lineinfile: dest=/etc/hosts
                  regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_default_ipv4.address }} {{ item }}"
                  state=present
      when: hostvars[item].ansible_default_ipv4.address is defined
      with_items: groups['all']
#    - name: "disable what we dont need" # doesnt seem to work...
#      yum: name=*
#           disablerepo=rhel-ha-for-rhel-7-server-htb-rpms,rhel-ha-for-rhel-7-server-rpms,rhel-rs-for-rhel-7-server-rpms,rhel-sap-for-rhel-7-server-rpms,rhel-lb-for-rhel-7-server-htb-rpms,rhel-7-server-rt-htb-rpms
#           state=present
    - name: "install docker and kubernetes"
      yum: name=docker,git,golang,bridge-utils
           enablerepo=rhel-7-server-extras-rpms,rhel-7-server-optional-rpms
           state=latest
    - name: "restat docker daemon"
      service: name=docker state=started
  handlers:
    - name: restart docker 
      service: name=docker state=restarted

- hosts: masters
  roles:
    - master

- hosts: minions
  roles:
    - minion 
